# This plugin is gathering some basic info about how many players/servers is using it.
# All data is collected anonymously and will not harm your server in any way.
# If you wish to opt-out of this service, though, just change this setting to true.
opt-out: false

# The name of the Eshop menu.
# Max 32 characters!
menu-name: EnchantGUI

# Payment currency can be one of two. Either 'money' for regular money (using Vault+Economy system)
# or 'xp' for XP levels.
# You can also put 'disable' to disable the economy-aspect of the plugin entirely.
payment-currency: money

# Enchant prices
# You can set a price for each individual level
# You can also use all: <price> to set a price for all enchant levels.
arrow_damage:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
    level8: 800
    level10: 1000
arrow_fire:
    level1: 100
arrow_infinite:
    level1: 100
arrow_knockback:
    level1: 100
    level2: 200
damage_all:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
damage_arthropods:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
damage_undead:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
depth_strider:
    level1: 100
    level2: 200
    level3: 300
dig_speed:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
durability:
    level1: 100
    level2: 200
    level3: 300
fire_aspect:
    level1: 100
    level2: 200
knockback:
    level1: 100
    level2: 200
loot_bonus_blocks:
    level1: 100
    level2: 200
    level3: 300
loot_bonus_mobs:
    level1: 100
    level2: 200
    level3: 300
luck:
    level1: 100
    level2: 200
    level3: 300
lure:
    level1: 100
    level2: 200
    level3: 300
oxygen:
    level1: 100
    level2: 200
    level3: 300
protection_environmental:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
protection_explosions:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
protection_fall:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
protection_fire:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
protection_projectile:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
silk_touch:
    level1: 100
thorns:
    level1: 100
    level2: 200
    level3: 300
water_worker:
    level1: 100
frost_walker:
    level1: 100
    level2: 200
mending:
    level1: 100